const C={bg:"#FAFBFC",card:"#FFFFFF",border:"#E2E8F0",accent:"#059669",accentLight:"#D1FAE5",accentDark:"#064E3B",text:"#1E293B",muted:"#64748B",light:"#94A3B8",code:"#1E1E2E",codeBg:"#F1F5F9",warn:"#F59E0B",warnBg:"#FFFBEB",info:"#3B82F6",infoBg:"#EFF6FF",green:"#10B981",red:"#EF4444",purple:"#7C3AED",orange:"#F97316",tipBg:"#F0FDF4",indigo:"#6366F1",violet:"#8B5CF6",sky:"#0EA5E9",amber:"#D97706"};
const F={h:"'Newsreader',Georgia,serif",b:"'Inter',-apple-system,sans-serif",m:"'JetBrains Mono','Fira Code',monospace"};
const GAMDiag=()=>(<svg viewBox="0 0 760 180" style={{width:"100%",display:"block"}}><rect width="760" height="180" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">GAM → GA²M → EBM: The Interpretability Lineage</text>{[{x:30,w:210,t:"GAM (1986)",f:"g(E[y]) = β₀ + Σ fᵢ(xᵢ)",d:"Additive univariate\nshape functions only",c:C.light},{x:275,w:210,t:"GA²M (2013)",f:"+ Σ fᵢⱼ(xᵢ, xⱼ)",d:"Add pairwise\ninteractions (FAST)",c:C.sky},{x:520,w:210,t:"EBM (2019)",f:"+ bagging + cyclic\nboosting + DP",d:"Modern ML training\nGlass-box accuracy",c:C.accent}].map((p,i)=>(<g key={i}>{i>0&&<text x={p.x-18} y="100" fill={C.accent} fontSize="18" textAnchor="middle">→</text>}<rect x={p.x} y="38" width={p.w} height="120" rx="6" fill={p.c} opacity="0.1" stroke={p.c} strokeWidth="1.5"/><text x={p.x+p.w/2} y="58" textAnchor="middle" fill={p.c} fontSize="11" fontFamily={F.b} fontWeight="700">{p.t}</text><text x={p.x+p.w/2} y="78" textAnchor="middle" fill={C.accent} fontSize="9" fontFamily={F.m}>{p.f}</text>{p.d.split("\n").map((ln,li)=>(<text key={li} x={p.x+p.w/2} y={100+li*15} textAnchor="middle" fill={C.text} fontSize="9" fontFamily={F.b}>{ln}</text>))}</g>))}<text x="380" y="172" textAnchor="middle" fill={C.light} fontSize="8" fontFamily={F.b}>Hastie & Tibshirani → Lou, Caruana et al. KDD 2012/2013 → Nori, Jenkins, Koch, Caruana 2019</text></svg>);
const TrainDiag=()=>(<svg viewBox="0 0 760 190" style={{width:"100%",display:"block"}}><rect width="760" height="190" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">Round-Robin Cyclic Training: One Feature at a Time</text>{[{x:40,l:"x₁",c:C.indigo},{x:140,l:"x₂",c:C.violet},{x:240,l:"x₃",c:C.sky},{x:340,l:"...",c:C.light},{x:440,l:"xₙ",c:C.amber},{x:540,l:"x₁",c:C.indigo},{x:640,l:"x₂",c:C.violet}].map((s,i)=>(<g key={i}><rect x={s.x} y="40" width="70" height="70" rx="6" fill={s.c} opacity="0.15" stroke={s.c} strokeWidth="1"/><text x={s.x+35} y="68" textAnchor="middle" fill={s.c} fontSize="16" fontFamily={F.m} fontWeight="700">{s.l}</text><text x={s.x+35} y="90" textAnchor="middle" fill={C.muted} fontSize="7" fontFamily={F.m}>small tree</text>{i<6&&<text x={s.x+88} y="75" fill={C.border} fontSize="14">→</text>}</g>))}<rect x="40" y="125" width="670" height="28" rx="4" fill={C.accentLight}/><text x="375" y="144" textAnchor="middle" fill={C.accentDark} fontSize="9" fontFamily={F.b}>Iteration 1 → Iteration 2 → ... → Iteration 5000 · LR=0.01 · Order doesn't matter</text><text x="380" y="182" textAnchor="middle" fill={C.light} fontSize="8" fontFamily={F.b}>Each feature's shape function builds up incrementally. The result is a lookup table: binned value → contribution.</text></svg>);
const ShapeDiag=()=>(<svg viewBox="0 0 760 190" style={{width:"100%",display:"block"}}><rect width="760" height="190" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">Shape Functions: The Core Interpretability Mechanism</text><rect x="40" y="42" width="320" height="120" rx="6" fill={C.codeBg}/><text x="200" y="60" textAnchor="middle" fill={C.text} fontSize="10" fontFamily={F.b} fontWeight="600">f(Age) — Global Shape</text><polyline points="60,142 100,138 140,125 180,105 220,88 260,84 300,92 340,115" fill="none" stroke={C.accent} strokeWidth="2.5"/><text x="60" y="157" fill={C.muted} fontSize="7" fontFamily={F.m}>20</text><text x="340" y="157" fill={C.muted} fontSize="7" fontFamily={F.m}>80</text><rect x="410" y="42" width="320" height="120" rx="6" fill={C.codeBg}/><text x="570" y="60" textAnchor="middle" fill={C.text} fontSize="10" fontFamily={F.b} fontWeight="600">f(Income) — Global Shape</text><polyline points="430,142 470,132 510,112 550,92 590,78 630,72 670,68 710,65" fill="none" stroke={C.sky} strokeWidth="2.5"/><text x="430" y="157" fill={C.muted} fontSize="7" fontFamily={F.m}>$20k</text><text x="710" y="157" fill={C.muted} fontSize="7" fontFamily={F.m}>$200k</text><text x="380" y="182" textAnchor="middle" fill={C.light} fontSize="8" fontFamily={F.b}>x-axis = feature value, y-axis = contribution. Global and exact — not local approximations like SHAP.</text></svg>);
const VsBox=()=>(<svg viewBox="0 0 760 180" style={{width:"100%",display:"block"}}><rect width="760" height="180" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">Two Paths to Explainable ML</text><rect x="30" y="38" width="335" height="115" rx="6" fill={C.accentLight} stroke={C.accent} strokeWidth="1.5"/><text x="197" y="56" textAnchor="middle" fill={C.accent} fontSize="10" fontFamily={F.b} fontWeight="700">Path A: Interpretable by Design (EBM)</text><text x="197" y="74" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>Shape functions ARE the explanation</text><text x="197" y="90" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>Global + local built in · Editable post-training</text><text x="197" y="110" textAnchor="middle" fill={C.green} fontSize="9" fontFamily={F.b} fontWeight="600">✓ One model, zero post-hoc tools</text><text x="197" y="130" textAnchor="middle" fill={C.muted} fontSize="8" fontFamily={F.b}>Additive constraint limits 3+ way interactions</text><rect x="395" y="38" width="335" height="115" rx="6" fill={C.codeBg} stroke={C.sky} strokeWidth="1.5"/><text x="562" y="56" textAnchor="middle" fill={C.sky} fontSize="10" fontFamily={F.b} fontWeight="700">Path B: Explain Post-Hoc (XGB + SHAP)</text><text x="562" y="74" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>Train black-box → Compute SHAP values</text><text x="562" y="90" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>Local per-instance · Needs dashboard layer</text><text x="562" y="110" textAnchor="middle" fill={C.red} fontSize="9" fontFamily={F.b} fontWeight="600">✗ Two systems to build and validate</text><text x="562" y="130" textAnchor="middle" fill={C.muted} fontSize="8" fontFamily={F.b}>Full interaction capacity, may be slightly more accurate</text><text x="380" y="172" textAnchor="middle" fill={C.light} fontSize="8" fontFamily={F.b}>If EBM accuracy is comparable, Path A is strictly preferable for regulated domains.</text></svg>);
const LandDiag=()=>(<svg viewBox="0 0 760 220" style={{width:"100%",display:"block"}}><rect width="760" height="220" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">Glass-Box Model Landscape</text><line x1="60" y1="200" x2="720" y2="200" stroke={C.border} strokeWidth="1"/><line x1="60" y1="200" x2="60" y2="42" stroke={C.border} strokeWidth="1"/><text x="390" y="216" textAnchor="middle" fill={C.light} fontSize="8" fontFamily={F.b}>Complexity →</text><text x="28" y="124" textAnchor="middle" fill={C.light} fontSize="8" fontFamily={F.b} transform="rotate(-90,28,124)">Accuracy →</text>{[{n:"Linear Reg",x:120,y:172,r:13,c:C.light},{n:"Decision Tree",x:175,y:155,r:12,c:C.light},{n:"RuleFit",x:235,y:135,r:11,c:C.amber},{n:"EBM",x:370,y:72,r:21,c:C.accent},{n:"GAMI-Net",x:440,y:82,r:13,c:C.violet},{n:"NAM",x:490,y:92,r:12,c:C.purple},{n:"NODE-GAM",x:535,y:96,r:11,c:C.sky},{n:"TabNet",x:590,y:86,r:12,c:C.orange},{n:"XGBoost",x:645,y:65,r:17,c:C.red},{n:"CALMs",x:420,y:105,r:10,c:C.indigo}].map((d,i)=>(<g key={i}><circle cx={d.x} cy={d.y} r={d.r} fill={d.c} opacity="0.4" stroke={d.c} strokeWidth="1.5"/><text x={d.x} y={d.y+d.r+11} textAnchor="middle" fill={C.text} fontSize="7" fontFamily={F.b} fontWeight="600">{d.n}</text></g>))}</svg>);
const ParamDiag=()=>(<svg viewBox="0 0 760 175" style={{width:"100%",display:"block"}}><rect width="760" height="175" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">Key EBM Hyperparameters</text>{[{x:25,w:170,t:"Training",p:"max_rounds: 5000\nlearning_rate: 0.01\nouter_bags: 16",c:C.accent},{x:205,w:170,t:"Tree Structure",p:"max_leaves: 3\nmin_samples_leaf: 2\nmax_bins: 256",c:C.sky},{x:385,w:170,t:"Interactions",p:"interactions: 10\nmax_interaction_bins: 32\n(FAST auto-detect)",c:C.violet},{x:565,w:170,t:"Constraints",p:"monotone_constraints\nfeature_types\nregularization",c:C.amber}].map((p,i)=>(<g key={i}><rect x={p.x} y="35" width={p.w} height="125" rx="6" fill={p.c} opacity="0.08" stroke={p.c} strokeWidth="1"/><text x={p.x+p.w/2} y="55" textAnchor="middle" fill={p.c} fontSize="10" fontFamily={F.b} fontWeight="700">{p.t}</text>{p.p.split("\n").map((ln,li)=>(<text key={li} x={p.x+p.w/2} y={75+li*16} textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.m}>{ln}</text>))}</g>))}</svg>);
const EditDiag=()=>(<svg viewBox="0 0 760 160" style={{width:"100%",display:"block"}}><rect width="760" height="160" fill="#fff" rx="8" stroke={C.border} strokeWidth="1"/><text x="380" y="22" textAnchor="middle" fill={C.text} fontSize="13" fontFamily={F.b} fontWeight="700">EBM Editing: Modify Shape Functions Post-Training</text><rect x="30" y="38" width="220" height="100" rx="6" fill={C.codeBg} stroke={C.red} strokeWidth="1" strokeDasharray="4,4"/><text x="140" y="56" textAnchor="middle" fill={C.red} fontSize="10" fontFamily={F.b} fontWeight="700">Before Edit</text><text x="140" y="74" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.m}>f(asthma=1) = -0.3</text><text x="140" y="92" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>Asthma DECREASES risk</text><text x="140" y="110" textAnchor="middle" fill={C.red} fontSize="8" fontFamily={F.b}>Confound: ICU admission bias</text><text x="280" y="88" fill={C.accent} fontSize="18">→</text><rect x="310" y="38" width="220" height="100" rx="6" fill={C.accentLight} stroke={C.green} strokeWidth="1.5"/><text x="420" y="56" textAnchor="middle" fill={C.green} fontSize="10" fontFamily={F.b} fontWeight="700">After Edit</text><text x="420" y="74" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.m}>f(asthma=1) = +0.1</text><text x="420" y="92" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>Corrected by clinician</text><text x="420" y="110" textAnchor="middle" fill={C.green} fontSize="8" fontFamily={F.b}>Safe for deployment</text><rect x="560" y="38" width="170" height="100" rx="6" fill={C.infoBg}/><text x="645" y="58" textAnchor="middle" fill={C.info} fontSize="10" fontFamily={F.b} fontWeight="700">Unique to EBMs</text><text x="645" y="78" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>No other ML model</text><text x="645" y="94" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>supports post-training</text><text x="645" y="110" textAnchor="middle" fill={C.text} fontSize="8.5" fontFamily={F.b}>editing of learned effects</text></svg>);
const Code=({children,title})=>(<div style={{margin:"24px 0",borderRadius:8,overflow:"hidden",border:`1px solid ${C.border}`}}>{title&&<div style={{background:C.code,padding:"8px 16px",fontFamily:F.m,fontSize:11,color:"#A78BFA",letterSpacing:"0.05em"}}>{title}</div>}<pre style={{background:C.code,padding:"16px 20px",margin:0,overflowX:"auto",fontSize:12.5,lineHeight:1.7,fontFamily:F.m,color:"#E2E8F0"}}><code>{children}</code></pre></div>);
const NB=({children,title,n})=>(<div style={{margin:"24px 0",borderRadius:8,overflow:"hidden",border:`1px solid ${C.border}`,borderLeft:`3px solid ${C.green}`}}><div style={{background:C.code,padding:"8px 16px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:F.m,fontSize:11,color:"#A78BFA",letterSpacing:"0.05em"}}>{title}</span><span style={{fontFamily:F.m,fontSize:10,color:C.green,background:"rgba(16,185,129,0.15)",padding:"2px 8px",borderRadius:4}}>Cell {n}</span></div><pre style={{background:C.code,padding:"16px 20px",margin:0,overflowX:"auto",fontSize:12.5,lineHeight:1.7,fontFamily:F.m,color:"#E2E8F0"}}><code>{children}</code></pre></div>);
const Callout=({type="info",title,children})=>{const s={info:{bg:C.infoBg,border:C.info,icon:"💡"},warn:{bg:C.warnBg,border:C.warn,icon:"⚠️"},tip:{bg:C.tipBg,border:C.green,icon:"✅"}}[type];return(<div style={{margin:"28px 0",padding:"20px 24px",background:s.bg,borderLeft:`4px solid ${s.border}`,borderRadius:"0 8px 8px 0"}}><div style={{fontFamily:F.b,fontSize:13,fontWeight:700,color:s.border,marginBottom:6}}>{s.icon} {title}</div><div style={{fontFamily:F.b,fontSize:14,lineHeight:1.7,color:C.text}} dangerouslySetInnerHTML={{__html:children}}/></div>);};
const Sec=({n,title,children})=>(<div style={{margin:"56px 0 0"}}><div style={{display:"flex",alignItems:"baseline",gap:12,marginBottom:20}}><span style={{fontFamily:F.m,fontSize:13,color:C.accent,fontWeight:700}}>§{n}</span><h2 style={{fontFamily:F.h,fontSize:28,fontWeight:700,color:C.text,lineHeight:1.2}}>{title}</h2></div>{children}</div>);
const P=({children})=>(<p style={{fontFamily:F.b,fontSize:16,lineHeight:1.8,color:C.text,margin:"0 0 18px"}} dangerouslySetInnerHTML={{__html:children}}/>);
const H3=({children})=>(<h3 style={{fontFamily:F.h,fontSize:20,fontWeight:600,color:C.text,margin:"28px 0 12px"}}>{children}</h3>);
const Cap=({children})=>(<div style={{fontFamily:F.b,fontSize:12,color:C.light,marginTop:8,marginBottom:28}}>{children}</div>);

export default function Article(){return(<div style={{background:C.bg,minHeight:"100vh"}}><style>{`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&family=Newsreader:ital,wght@0,400;0,600;0,700;1,400&display=swap');*{box-sizing:border-box;margin:0;padding:0}body{background:${C.bg}}`}</style>
<div style={{background:C.accent,padding:"12px 24px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:8}}><span style={{fontFamily:F.m,fontSize:11,color:"#D1FAE5",letterSpacing:"0.1em",textTransform:"uppercase"}}>Technical Encyclopaedic Article</span><span style={{fontFamily:F.m,fontSize:11,color:"#D1FAE5"}}>Interpretable ML · Glass-Box · GAMs · Python</span></div>
<div style={{maxWidth:820,margin:"0 auto",padding:"60px 24px 0"}}><div style={{fontFamily:F.m,fontSize:12,color:C.accent,fontWeight:600,letterSpacing:"0.08em",marginBottom:12}}>EXPLAINABLE BOOSTING MACHINES</div><h1 style={{fontFamily:F.h,fontSize:"clamp(28px,4.5vw,44px)",fontWeight:700,color:C.text,lineHeight:1.15,marginBottom:20}}>The Glass-Box That Rivals the Black Box</h1><p style={{fontFamily:F.b,fontSize:18,color:C.muted,lineHeight:1.6,maxWidth:680,marginBottom:12}}>As accurate as gradient boosting, as interpretable as linear regression. Microsoft Research's EBM makes the case that you don't need SHAP if the model explains itself.</p><div style={{fontFamily:F.b,fontSize:13,color:C.light,marginBottom:40}}>InterpretML 0.6+ · Python 3.9+ · scikit-learn API · EU AI Act context</div><div style={{height:1,background:C.border,marginBottom:20}}/></div>
<div style={{maxWidth:820,margin:"0 auto",padding:"0 24px 80px"}}>

<Sec n="1" title="The Interpretability Question"><P>{`You've trained an XGBoost model for credit scoring. AUC 0.923 on your holdout set. Then compliance asks: "For every denied application, provide the specific features and their exact contributions that led to the denial." You reach for SHAP — compute Shapley values, build a Shapash dashboard, generate an audit report. It works, but it's two systems: the model that decides, and the explanation that rationalises the decision post-hoc. The explanation is approximate, local, and computed after the fact.`}</P><P>{`There is another path. Instead of building a black-box model and explaining it, you build a model that is <em>interpretable by design</em> — one whose internal structure is directly human-readable, where each feature's effect is a curve you can plot, inspect, and edit. And this model matches the black box's accuracy. This is the <strong>Explainable Boosting Machine (EBM)</strong>, developed at Microsoft Research by Rich Caruana and collaborators. It is a tree-based, cyclic gradient boosting Generalised Additive Model with automatic interaction detection.`}</P><P>{`This article covers everything at encyclopaedic depth: the mathematical lineage from GAMs through GA²M to EBM; the round-robin training algorithm; shape functions and their visualisation; the accuracy debate with evidence; the InterpretML library in full; four production use cases; the competitive landscape of glass-box models; model editing; and an honest decision framework. Every concept section contains a runnable notebook cell — Cells 0–9 form a complete end-to-end example.`}</P></Sec>

<NB title="00_setup.py" n={0}>{`# pip install interpret scikit-learn pandas numpy
from interpret.glassbox import ExplainableBoostingClassifier
from interpret import show
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import pandas as pd, numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
cols = ["Age","WorkClass","fnlwgt","Education","EducationNum",
        "MaritalStatus","Occupation","Relationship","Race","Gender",
        "CapitalGain","CapitalLoss","HoursPerWeek","NativeCountry","Income"]
df = pd.read_csv(url, header=None, names=cols, na_values=" ?", skipinitialspace=True).dropna()
X = df.drop("Income", axis=1)
y = (df["Income"] == ">50K").astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Train: {"{"}{len(X_train)}{"}"}, Test: {"{"}{len(X_test)}{"}"}, Features: {"{"}{X.shape[1]}{"}"}")`}</NB>

<Callout type="info" title="Notebook Map">{`<strong>Cells 0–9</strong>: <code>Cell 0</code> Setup (§1) · <code>Cell 1</code> Train (§4) · <code>Cell 2</code> Global Explain (§5) · <code>Cell 3</code> Local Explain (§5) · <code>Cell 4</code> Interactions (§6) · <code>Cell 5</code> Tuning (§8) · <code>Cell 6</code> Monotonic (§9) · <code>Cell 7</code> Editing (§10) · <code>Cell 8</code> vs XGBoost (§12) · <code>Cell 9</code> Deploy (§16)`}</Callout>

<Sec n="2" title="Generalised Additive Models: The Mathematical Foundation"><P>{`An EBM is a Generalised Additive Model (GAM). GAMs were introduced by Hastie and Tibshirani (1986) as an extension of linear models: <code>g(E[y]) = β₀ + f₁(x₁) + f₂(x₂) + ... + fₙ(xₙ)</code>, where g is a link function (identity for regression, logit for classification) and each fᵢ is a univariate "shape function" learned from data. The additive structure is the source of interpretability: each feature contributes independently, so you can visualise fᵢ(xᵢ) as a curve — x-axis is feature value, y-axis is contribution to prediction — and inspect it directly. No post-hoc approximation needed.`}</P><GAMDiag/><Cap>The lineage: GAMs provide the additive framework. GA²M (Lou et al., KDD 2013) adds pairwise interactions via the FAST algorithm. EBMs add modern ML training — bagging, cyclic gradient boosting, optional differential privacy.</Cap><P>{`The limitation of pure GAMs is accuracy. Because each feature acts independently, GAMs cannot capture interactions — where feature A's effect depends on feature B's value. Lou, Caruana, Gehrke, and Hooker addressed this in their KDD 2013 paper with GA²M: <code>g(E[y]) = β₀ + Σfᵢ(xᵢ) + Σfᵢⱼ(xᵢ,xⱼ)</code>. The pairwise terms fᵢⱼ are 2D heatmaps — still visualisable and interpretable, but capturing the most important non-linear interactions. Their FAST algorithm efficiently ranks all n(n-1)/2 possible pairs to find the top-k worth including.`}</P><P>{`The result was surprising: GA²M models "substantially close the accuracy gap between unintelligible full-complexity models such as random forests and GAMs" (Lou et al., KDD 2013). On some datasets, GA²M outperformed the best random forest. This was the empirical foundation for the EBM: add modern training techniques to the GA²M framework and match black-box accuracy while retaining full interpretability.`}</P></Sec>

<Sec n="3" title="The EBM Training Algorithm: Round-Robin Cyclic Boosting"><P>{`The key innovation in EBM's training is <strong>cyclic, one-feature-at-a-time gradient boosting</strong>. Unlike XGBoost, which builds each tree using all features simultaneously (creating complex multi-feature splits), EBM trains a small tree on just one feature at a time, rotating through all features in round-robin fashion across thousands of iterations. In iteration 1, it fits a small tree to x₁'s residuals, then x₂'s, then x₃'s, ..., then xₙ's. In iteration 2, it repeats. This continues for 5,000 rounds with a very low learning rate (0.01).`}</P><TrainDiag/><Cap>Each iteration trains one small tree per feature on current residuals. Low learning rate (0.01) ensures order doesn't matter. Shape functions accumulate across thousands of iterations.</Cap><P>{`The low learning rate is critical: each tree's contribution is scaled by 0.01, so the model takes tiny steps. The order in which features are processed within a cycle has negligible effect. Each feature's shape function fᵢ is the sum of all small trees trained on that feature across all iterations — effectively a lookup table: for each binned value of xᵢ, there's a contribution to the prediction. This IS the shape function — it's the actual model, not an approximation.`}</P><P>{`After main effects are learned, EBM applies the FAST algorithm to detect top-k pairwise interactions (default: 10), trained the same way on feature pairs. Bagging (outer_bags=16) wraps the entire process, training multiple EBMs on bootstrap samples and averaging them for stability and confidence intervals on shape functions.`}</P></Sec>

<Sec n="4" title="InterpretML: The Library"><P>{`InterpretML is MIT-licensed, created by Samuel Jenkins, Harsha Nori, Paul Koch, and Rich Caruana. It provides <code>ExplainableBoostingClassifier</code> and <code>ExplainableBoostingRegressor</code> with a scikit-learn-compatible API. EBMs handle mixed feature types natively — continuous features are automatically binned (256 bins), categoricals are handled directly without one-hot encoding, ordinals preserve ordering. You pass raw DataFrames with string columns and the model handles everything.`}</P><P>{`The library includes an interactive visualisation system (<code>show()</code>) that renders global shape function plots, local waterfall explanations, and interaction heatmaps in Jupyter. For programmatic access, <code>ebm.term_names_</code>, <code>ebm.term_scores_</code>, and <code>ebm.term_features_</code> expose the full model internals — every shape function, every interaction, every contribution value.`}</P><P>{`InterpretML also includes post-hoc explanation tools (SHAP, LIME, PDP) under the same API, making it a unified framework for comparing glass-box and black-box explainability. But the EBM is the library's unique contribution — no other framework offers a model this accurate that explains itself by construction.`}</P><NB title="01_train_ebm.py" n={1}>{`ebm = ExplainableBoostingClassifier(
    max_rounds=5000, learning_rate=0.01, max_leaves=3,
    min_samples_leaf=2, interactions=10, outer_bags=16,
    max_bins=256, random_state=42,
)
ebm.fit(X_train, y_train)
auc = roc_auc_score(y_test, ebm.predict_proba(X_test)[:, 1])
print(f"EBM AUC: {"{"}{auc:.4f}{"}"}")
# Typical: ~0.927 on Adult Income (XGBoost: ~0.930)`}</NB></Sec>

<Sec n="5" title="Shape Functions: The Core Interpretability Mechanism"><P>{`Each shape function fᵢ(xᵢ) is a learned mapping from feature values to prediction contributions. For continuous features, it's a step function over bins. For categoricals, it's a bar chart. These are the <em>actual model internals</em>, not post-hoc approximations. When you view a shape plot, you see exactly how the model uses that feature — globally, for every prediction, with zero approximation error.`}</P><ShapeDiag/><Cap>Two global shape functions from an EBM. Left: f(Age) is non-linear — peaks around 50. Right: f(Income) is monotonically increasing and saturating. These are exact learned effects, not SHAP approximations.</Cap><P>{`This is fundamentally different from SHAP. A SHAP waterfall shows attribution for a <em>single prediction</em> — local and approximate (for non-tree models). An EBM shape function shows the <em>global</em> effect across all predictions — exact and complete. You see at a glance: "Income above $80k always increases the prediction, saturating above $150k." For local explanations, EBM reads the contribution from each shape function at the instance's feature values and sums — exact, instantaneous, no Shapley sampling.`}</P><P>{`The interactive dashboard (<code>show(ebm.explain_global())</code>) renders all shape functions with confidence intervals. Domain experts can inspect each curve: does f(Age) make clinical sense? Does f(Credit Score) match regulatory expectations? This direct inspection is impossible with black-box models — you can only inspect SHAP approximations, which carry sampling noise and may disagree across methods.`}</P>
<NB title="02_global_explain.py" n={2}>{`global_exp = ebm.explain_global()
# show(global_exp)  # interactive dashboard in Jupyter

# Programmatic access to shape functions
for i in range(min(5, len(ebm.term_names_))):
    name = ebm.term_names_[i]
    scores = ebm.term_scores_[i]
    print(f"{"{"}{name:25s}{"}"} min: {"{"}{scores.min():.3f}{"}"}, max: {"{"}{scores.max():.3f}{"}"}")

print(f"\\nIntercept: {"{"}{ebm.intercept_[0]:.4f}{"}"}")
print(f"Main effects: {"{"}{sum(1 for t in ebm.term_features_ if len(t)==1)}{"}"}")
print(f"Interactions:  {"{"}{sum(1 for t in ebm.term_features_ if len(t)==2)}{"}"}")`}</NB>
<NB title="03_local_explain.py" n={3}>{`local_exp = ebm.explain_local(X_test.iloc[:5], y_test.iloc[:5])
# show(local_exp)  # interactive waterfall in Jupyter

# Programmatic: contributions for one instance
prediction = ebm.predict_proba(X_test.iloc[[0]])[0, 1]
print(f"P(>50K): {"{"}{prediction:.3f}{"}"}")
local_data = local_exp.data(0)
names, scores = local_data["names"], local_data["scores"]
ranked = sorted(range(len(scores)), key=lambda i: abs(scores[i]), reverse=True)
print("\\nTop features:")
for idx in ranked[:8]:
    print(f"  {"{"}{names[idx]:30s}{"}"} {"{"}{scores[idx]:+.4f}{"}"}")`}</NB></Sec>

<Sec n="6" title="Pairwise Interactions and the FAST Algorithm"><P>{`Pure additive models miss interactions — where feature A's effect depends on feature B. The classic example: education's effect on income depends on occupation. A PhD in engineering has a different income effect than a PhD in poetry. EBM captures this via pairwise interaction terms fᵢⱼ(xᵢ,xⱼ), visualised as 2D heatmaps.`}</P><P>{`The FAST algorithm (Lou et al., KDD 2013) makes this tractable. With n features, there are n(n-1)/2 possible pairs. FAST ranks all pairs by residual improvement using greedy forward selection, adds the top-k (default: 10). Because only a few interactions are included, the model stays interpretable. Empirically, the top 10 capture most interaction signal; going beyond 20 rarely helps.`}</P><P>{`Each interaction heatmap is directly inspectable: colour represents the joint contribution of two feature values. A compliance officer can verify that the Education × Occupation interaction makes business sense — no post-hoc tool needed, no approximation, no sampling artefacts.`}</P><NB title="04_interactions.py" n={4}>{`interaction_terms = [(i,t) for i,t in enumerate(ebm.term_features_) if len(t)==2]
print(f"Detected {"{"}{len(interaction_terms)}{"}"} pairwise interactions:")
for idx, features in interaction_terms:
    name = ebm.term_names_[idx]
    importance = np.abs(ebm.term_scores_[idx]).mean()
    print(f"  {"{"}{name:40s}{"}"} |contrib|: {"{"}{importance:.4f}{"}"}")`}</NB></Sec>

<Sec n="7" title="The Accuracy-Interpretability Debate"><P>{`Cynthia Rudin's "Stop Explaining Black Box Machine Learning Models for High Stakes Decisions and Use Interpretable Models Instead" (Nature Machine Intelligence, 2019) argued that the accuracy-interpretability tradeoff is often a myth. For structured tabular data, interpretable models achieve comparable accuracy — and the small gap, if it exists, is not worth the risk of deploying an unexplainable system in healthcare, criminal justice, or finance.`}</P><VsBox/><Cap>Two paths to explainable ML. Path A (EBM): interpretable by design, explanations built in, editable. Path B (XGB + SHAP): two systems to build, explain approximately. For regulated domains, Path A is strictly preferable when accuracy matches.</Cap><P>{`The empirical evidence: Lou et al. (KDD 2012, 2013) showed GA²M matching random forest accuracy. Caruana et al. (KDD 2015) applied GA²Ms to real healthcare — ICU mortality, pneumonia risk, readmission — achieving state-of-the-art accuracy while revealing bugs black boxes hid. The famous case: a neural network learned asthma <em>decreased</em> pneumonia mortality risk — because asthmatics were admitted to ICU and received better care (a confound). The GA²M's shape function showed this as a negative contribution, allowing clinicians to catch and correct it. Chang et al. (NeurIPS 2021) benchmarked EBMs within 1-2% AUC of gradient boosted trees on most datasets.`}</P><P>{`Where EBMs genuinely lose: very high-dimensional feature spaces (500+ features), tasks dominated by higher-order interactions (3-way+), very large datasets where cyclic training is slower than XGBoost's parallel approach, and tasks where additive + pairwise structure cannot capture the signal. These cases exist but are a minority of production tabular problems.`}</P></Sec>

<Sec n="8" title="Hyperparameter Tuning"><ParamDiag/><Cap>Key EBM hyperparameters: training control, tree structure, interaction detection, and domain constraints.</Cap><P>{`<strong>max_rounds</strong> (5000): boosting iterations per cycle — higher = finer shapes. <strong>learning_rate</strong> (0.01): step size — lower = smoother. <strong>max_leaves</strong> (3): tree depth per step — 3 leaves = one split, smooth shapes. <strong>interactions</strong> (10): auto-detected pairs. <strong>outer_bags</strong> (16): bagging for stability. <strong>max_bins</strong> (256): binning resolution. For best results, the InterpretML team recommends: 100 outer bags, 5000 rounds, LR 0.01.`}</P><P>{`The most impactful hyperparameter for accuracy is <strong>interactions</strong>: increasing from 10 to 50 can noticeably improve accuracy on datasets with many interacting features, at the cost of more heatmaps to inspect. <strong>max_leaves</strong> affects smoothness: 3 produces smooth curves; increasing to 8 or 16 allows sharper discontinuities that may overfit.`}</P><NB title="05_tuning.py" n={5}>{`ebm_tuned = ExplainableBoostingClassifier(
    max_rounds=5000, learning_rate=0.01, max_leaves=3,
    interactions=20, outer_bags=25, max_bins=256,
    min_samples_leaf=2, random_state=42,
)
ebm_tuned.fit(X_train, y_train)
auc_t = roc_auc_score(y_test, ebm_tuned.predict_proba(X_test)[:, 1])
print(f"Tuned EBM AUC: {"{"}{auc_t:.4f}{"}"}")`}</NB></Sec>

<Sec n="9" title="Monotonic Constraints"><P>{`In many domains, relationships are known: higher credit score must decrease default risk; higher dosage must increase drug effect; more experience must increase salary. EBMs support <strong>monotonic constraints</strong> — the shape function for a constrained feature is guaranteed monotonically increasing or decreasing. A compliance officer can verify the constraint holds globally.`}</P><P>{`This is more powerful than SHAP-based verification. With SHAP, you can check that the <em>average</em> contribution of credit score is negative — but individual instances may violate monotonicity. With EBM monotonic constraints, the guarantee is structural — no instance can violate it, because the shape function itself is monotonic.`}</P><NB title="06_monotonic.py" n={6}>{`constraints = [0] * X_train.shape[1]
edu_idx = list(X_train.columns).index("EducationNum")
hours_idx = list(X_train.columns).index("HoursPerWeek")
constraints[edu_idx] = 1   # increasing
constraints[hours_idx] = 1 # increasing

ebm_c = ExplainableBoostingClassifier(
    monotone_constraints=constraints, random_state=42)
ebm_c.fit(X_train, y_train)
auc_c = roc_auc_score(y_test, ebm_c.predict_proba(X_test)[:, 1])
print(f"Constrained AUC: {"{"}{auc_c:.4f}{"}"}")
print("EducationNum shape guaranteed monotonically increasing")`}</NB></Sec>

<Sec n="10" title="Model Editing: Fixing What the Model Got Wrong"><P>{`EBMs are the only ML model that supports <strong>post-training editing of learned relationships</strong>. Because each feature's effect is a lookup table, a domain expert can directly modify the values — changing the contribution of a specific feature level, flattening a region of a shape function, or removing a learned confound entirely. This is not retraining — it's direct surgery on the model's internals.`}</P><EditDiag/><Cap>The pneumonia-asthma confound: the model learned asthma decreases risk (left) because asthmatics received ICU care. A clinician edits the shape function to correct this (right). No other ML model supports this.</Cap><P>{`The canonical example is from Caruana et al. (KDD 2015): the pneumonia risk model learned that asthma was a <em>protective</em> factor — patients with asthma who got pneumonia had lower mortality. Why? Because hospital protocols sent asthmatic pneumonia patients straight to ICU, where they received better care. A black-box model hides this confound. An EBM reveals it as a visible negative contribution in the asthma shape function. A clinician sees it, recognises the confound, and edits the shape function to set asthma's contribution to positive or zero — making the model safe for deployment.`}</P><P>{`This editing capability extends to fairness. If a shape function shows a learned bias (e.g., a demographic feature contributing to a lending decision), you can zero it out without retraining. The model's accuracy on the remaining features is preserved because the additive structure means removing one term doesn't affect the others.`}</P><NB title="07_editing.py" n={7}>{`# Model editing: modify a shape function post-training
# Example: flatten CapitalGain's contribution above $10k
import copy
ebm_edited = copy.deepcopy(ebm)

# Find CapitalGain term
for i, name in enumerate(ebm_edited.term_names_):
    if name == "CapitalGain":
        scores = ebm_edited.term_scores_[i]
        # Get bin edges
        bins = ebm_edited.bins_[i][0]
        # Flatten: set all contributions above a threshold to constant
        threshold_bin = len(bins) // 2
        scores[threshold_bin:] = scores[threshold_bin]
        print(f"Edited {"{"}{name}{"}"}: flattened top half of shape function")
        break

# The edited model is still valid — just re-evaluate
auc_e = roc_auc_score(y_test, ebm_edited.predict_proba(X_test)[:, 1])
print(f"Edited EBM AUC: {"{"}{auc_e:.4f}{"}"}")`}</NB></Sec>

<Sec n="11" title="Use Case: Healthcare Risk Prediction"><P>{`<strong>Safety-critical, FDA-adjacent.</strong> A hospital builds a pneumonia mortality risk model with 38 features — demographics, vital signs, lab results, comorbidities. The model must be inspectable by clinicians before deployment. An EBM achieves AUC 0.91 on the holdout set — matching the XGBoost baseline. The shape function for temperature reveals a U-shaped curve: both hypothermia and high fever increase risk. The shape function for blood pressure shows a threshold effect at 90 mmHg systolic. Both match clinical knowledge.`}</P><P>{`<strong>The confound discovery:</strong> The asthma shape function shows a negative contribution — asthma appears to decrease risk. A pulmonologist recognises the ICU admission confound (Caruana et al., KDD 2015): asthmatics with pneumonia are flagged for ICU, receiving better care, which reduces mortality in the training data. The clinician edits the shape function to set asthma's contribution to slightly positive. The model is now safe for deployment. With a black-box model, this confound would have been invisible.`}</P><P>{`<strong>Regulatory trail:</strong> The shape function plots are included in the model validation documentation. Each feature's learned effect is reviewed by a clinical committee. The documentation satisfies FDA software-as-medical-device guidelines and EU AI Act high-risk transparency requirements. No post-hoc explanation tool needed.`}</P></Sec>

<Sec n="12" title="Use Case: Credit Scoring"><P>{`<strong>Regulation-driven.</strong> Under the Equal Credit Opportunity Act (ECOA), lenders must provide specific adverse action reasons for every denied application: "Your application was declined because: (1) insufficient income, (2) short credit history, (3) high debt-to-income ratio." SHAP values can generate these reasons approximately, but EBM shape functions generate them exactly — each feature's contribution is read directly from the lookup table.`}</P><P>{`An EBM trained on 22 credit features achieves AUC 0.89 — within 0.5% of XGBoost (0.893). The shape function for credit_score is monotonically decreasing (enforced via constraint). The shape function for debt_to_income shows a sharp threshold at 0.43 where risk increases dramatically. The shape function for years_of_history is approximately logarithmic — marginal benefit decreases after 7 years. All three match domain knowledge and can be directly cited in adverse action notices.`}</P>
<NB title="08_vs_xgboost.py" n={8}>{`# Compare EBM vs XGBoost on the same data
try:
    from xgboost import XGBClassifier
    # XGBoost requires encoded categoricals
    X_train_enc = X_train.copy()
    X_test_enc = X_test.copy()
    for col in X_train_enc.select_dtypes(include="object").columns:
        X_train_enc[col] = X_train_enc[col].astype("category").cat.codes
        X_test_enc[col] = X_test_enc[col].astype("category").cat.codes

    xgb = XGBClassifier(n_estimators=500, max_depth=6, learning_rate=0.1,
                         random_state=42, eval_metric="logloss")
    xgb.fit(X_train_enc, y_train)
    auc_xgb = roc_auc_score(y_test, xgb.predict_proba(X_test_enc)[:, 1])
    print(f"XGBoost AUC: {"{"}{auc_xgb:.4f}{"}"}")
    print(f"EBM AUC:     {"{"}{auc:.4f}{"}"}")
    print(f"Difference:  {"{"}{abs(auc_xgb - auc):.4f}{"}"}")
except ImportError:
    print("XGBoost not installed — install with: pip install xgboost")`}</NB><P>{`<strong>The deployment advantage:</strong> With XGBoost, the compliance team needs SHAP + a dashboard + a report generator + ongoing explanation validation. With EBM, the model IS the explanation. One system to build, validate, deploy, and audit. For a lending institution processing thousands of applications daily, this operational simplicity is a significant cost reduction.`}</P></Sec>

<Sec n="13" title="Use Case: Insurance Underwriting"><P>{`<strong>MAIF's domain.</strong> An insurer models claim frequency with policyholder demographics, vehicle attributes, driving history, and geographic risk factors. Currently using XGBoost + Shapash for post-hoc explanations. Could an EBM replace the entire stack? The EBM achieves comparable accuracy (MAE within 2% of XGBoost) and its shape functions map directly to actuarial intuition: f(driver_age) shows the well-known U-curve (young and elderly drivers have higher risk), f(vehicle_age) shows increasing risk with age, and f(annual_mileage) shows a monotonically increasing risk.`}</P><P>{`Under GDPR Article 22 and the EU AI Act, automated pricing decisions must be explainable to the policyholder. EBM shape functions provide this: "Your premium increased because: Vehicle Age: 12 years (+€45), Annual Mileage: 25,000 km (+€32), Urban Postcode: Yes (+€28)." These are exact model contributions, not SHAP approximations. The compliance team reviews global shape functions at each model refresh — verifying no protected attributes have proxy effects.`}</P><P>{`<strong>When EBM replaces Shapash + XGBoost:</strong> when the accuracy gap is negligible and regulatory explainability is the primary concern. <strong>When it doesn't:</strong> when the portfolio has complex multi-way interaction patterns (weather × geography × vehicle type × time of year) that the pairwise constraint cannot capture — in which case XGBoost + Shapash remains the better architecture.`}</P></Sec>

<Sec n="14" title="Use Case: Predictive Maintenance"><P>{`<strong>Physics-validatable.</strong> A manufacturing plant models equipment failure probability using sensor data: temperature, vibration, pressure, operating hours, maintenance history. The domain expert (a mechanical engineer) needs to verify that the model's learned relationships match physical reality. An EBM's shape function for temperature shows: flat below 70°C, gradual increase 70–85°C, sharp increase above 85°C. The engineer confirms: this matches the thermal degradation curve for the bearing material. If f(temperature) had shown a random or non-physical pattern, the engineer would reject the model immediately.`}</P><P>{`With XGBoost, the engineer would see a SHAP beeswarm plot showing that high temperature generally increases failure risk — but not the <em>specific functional form</em> of the relationship. The EBM shape function shows the exact learned curve, which can be compared point-by-point against the material science data sheet. This is interpretability that goes beyond "which features matter" to "what specific relationship did the model learn — and is it physically correct?"'`}</P><P>{`<strong>The editing use case:</strong> The vibration sensor has a known calibration drift above 15 kHz. The engineer edits f(vibration) to flatten the contribution above 15 kHz — removing the artefact without retraining. The model's accuracy on the remaining features is preserved because the additive structure means changes to one term don't cascade.`}</P></Sec>

<Sec n="15" title="Competitive Landscape"><LandDiag/><Cap>Glass-box model landscape. EBM (green, centre) leads on accuracy among interpretable models. GAMI-Net, NAM, NODE-GAM are neural GAM variants. XGBoost (red, right) is the black-box accuracy ceiling. CALMs (arXiv 2602.16503, Feb 2026) are the newest competitor.</Cap><P>{`<strong>EBM vs. linear/logistic regression:</strong> EBMs are strictly better when non-linear relationships exist (they almost always do). Regression wins only when extreme simplicity is required (coefficient-based interpretation, massive datasets, sub-millisecond training). <strong>EBM vs. XGBoost + SHAP:</strong> comparable accuracy on most tabular datasets, but EBM provides exact global + local explanations by construction. XGBoost may be 1-3% more accurate on interaction-heavy tasks. <strong>EBM vs. GAMI-Net</strong> (neural GAM, Zebin Yang et al.): GAMI-Net uses neural networks for shape functions instead of trees; theoretically more flexible but harder to train and less stable. <strong>EBM vs. NAM</strong> (Neural Additive Models, Google Brain, Agarwal et al. 2021): similar concept with neural networks; less mature, higher computational cost. <strong>EBM vs. NODE-GAM:</strong> differentiable oblivious trees; research-stage. <strong>EBM vs. RuleFit:</strong> rule-based, less accurate, but human-readable rules. <strong>EBM vs. CALMs</strong> (arXiv 2602.16503, Feb 2026): Conditionally Additive Local Models use region-specific shape functions — multiple univariate effects per feature, each active in different input regions. CALMs claim to balance GAM interpretability with GA²M accuracy.`}</P><Callout type="info" title="When EBM wins vs. alternatives">{`<strong>EBM wins:</strong> tabular data, under 500 features, need exact global explanations, regulatory compliance, model editing, mixed feature types. <strong>XGBoost wins:</strong> interaction-heavy tasks, 500+ features, training speed priority. <strong>Linear regression wins:</strong> extreme simplicity needed, massive datasets, coefficient interpretation.`}</Callout></Sec>

<Sec n="16" title="Production Deployment"><P>{`EBMs are one of the fastest models at prediction time. Because prediction involves simple lookups (bin the feature value, read the contribution from the lookup table) and a single sum, EBMs execute in microseconds per instance — often faster than tree ensembles that must traverse hundreds of decision trees. The model's memory footprint is also small: just the lookup tables and intercept.`}</P><P>{`For deployment, EBMs are serialised via pickle or joblib, loaded in a Flask/FastAPI endpoint, and serve predictions with per-instance explanations at no additional cost. Every prediction comes with a free, exact decomposition into feature contributions. No SHAP computation, no TreeSHAP overhead, no explanation latency. The shape function lookup that produces the prediction IS the explanation.`}</P><NB title="09_deploy.py" n={9}>{`import pickle
# Save
with open("ebm_model.pkl", "wb") as f:
    pickle.dump(ebm, f)
print("Model saved: ebm_model.pkl")

# Load and predict with explanation
with open("ebm_model.pkl", "rb") as f:
    ebm_loaded = pickle.load(f)

instance = X_test.iloc[[0]]
pred = ebm_loaded.predict_proba(instance)[0, 1]
local = ebm_loaded.explain_local(instance)
data = local.data(0)
print(f"Prediction: {"{"}{pred:.3f}{"}"}")
print("Explanation (top 5 features):")
ranked = sorted(range(len(data["scores"])), key=lambda i: abs(data["scores"][i]), reverse=True)
for i in ranked[:5]:
    print(f"  {"{"}{data['names'][i]:25s}{"}"} {"{"}{data['scores'][i]:+.4f}{"}"}")
# Zero additional latency — the explanation IS the prediction`}</NB>
<Callout type="tip" title="End of notebook">{`Cells 0–9 complete: setup → train → global explain → local explain → interactions → tuning → monotonic constraints → model editing → XGBoost comparison → deployment. Copy green-bordered cells in order for a working end-to-end example.`}</Callout></Sec>

<Sec n="17" title="Advanced Topics"><P>{`<strong>Differential privacy:</strong> EBMs are the only glass-box model with built-in DP-SGD support (Nori et al., 2021). By adding calibrated noise to the gradient updates during training, EBMs can provide formal privacy guarantees — critical for healthcare and financial applications where training data contains sensitive information. <strong>EBM merging:</strong> because shape functions are lookup tables, multiple EBMs trained on different data partitions can be averaged — producing a merged model without sharing raw data. This enables federated-like learning for privacy-sensitive deployments. <strong>Calibration:</strong> EBMs produce well-calibrated probabilities out of the box due to the additive structure — the predicted probabilities closely match actual event frequencies. <strong>TalkToEBM</strong> (Bordt et al., XAI4Sci AAAI-24): a natural language interface that converts EBM shape functions to text and asks LLMs to describe, summarise, and audit models.`}</P></Sec>

<Sec n="18" title="The People Behind EBMs"><P>{`<strong>Rich Caruana</strong> (Microsoft Research): Senior Principal Researcher, 30+ years on intelligible models. Created EBMs. His "friends don't let friends deploy black-box models" talk at KDD is the manifesto of the interpretable ML movement. <strong>Yin Lou</strong> (Georgia Tech → Airbnb → LinkedIn): first author of GA²M and FAST (KDD 2012, 2013) — the algorithms EBMs build upon. <strong>Cynthia Rudin</strong> (Duke): "Stop Explaining Black Box Models" (Nature MI 2019) — the theoretical and ethical argument for interpretable models. AAAI 2019 Squirrel AI Award for advancing AI for the benefit of humanity. <strong>Harsha Nori, Samuel Jenkins, Paul Koch</strong> (Microsoft): InterpretML library architects and maintainers. <strong>Chun-Hao Chang, Sarah Tan, Ben Lengerich, Anna Goldenberg</strong>: "How Interpretable and Trustworthy are GAMs?" (NeurIPS 2021) — the definitive benchmark. InterpretML is part of Microsoft's Responsible AI Toolbox alongside Fairlearn, Error Analysis, and DiCE.`}</P></Sec>

<Sec n="19" title="Decision Framework"><div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:8,padding:28,margin:"20px 0"}}><div style={{fontFamily:F.b,fontSize:15,lineHeight:2.2,color:C.text}}><div style={{marginBottom:8}}><span style={{color:C.green,fontWeight:700,fontSize:16}}>✓ Use EBMs when:</span></div><div style={{paddingLeft:24,fontSize:14,lineHeight:2}}>Tabular data with under 500 features.<br/>Regulatory compliance requires exact feature-level explanations (ECOA, GDPR, EU AI Act).<br/>Domain experts need to inspect and validate learned relationships.<br/>Model editing is required (fix confounds, remove bias, inject domain knowledge).<br/>Mixed feature types (continuous + categorical + ordinal) without preprocessing.<br/>Calibrated probabilities are needed out of the box.<br/>Deployment needs per-prediction explanations at zero additional latency.</div><div style={{marginTop:20,marginBottom:8}}><span style={{color:C.red,fontWeight:700,fontSize:16}}>✗ Consider alternatives when:</span></div><div style={{paddingLeft:24,fontSize:14,lineHeight:2}}>500+ features (EBM training scales linearly with features but cyclic approach is slow) → XGBoost.<br/>Higher-order interactions (3-way+) dominate the signal → XGBoost or neural networks.<br/>Very large datasets where training time matters → XGBoost is faster to train.<br/>Non-tabular data (images, text, sequences) → deep learning.<br/>Extreme simplicity needed (coefficient interpretation) → logistic regression.<br/>Unstructured prediction tasks where interpretability is not required.</div></div></div><P>{`EBMs represent a genuine paradigm shift: instead of building an accurate model and explaining it afterward, you build a model that is accurate <em>and</em> self-explaining from the start. In a regulatory environment where the EU AI Act requires that "where an interpretable model achieves comparable accuracy, it should be preferred," EBMs are not just a technical option — they are the compliance-first architecture. The question for every new tabular ML project in 2026 should not be "which black box?" but "does an EBM match the black box?" If it does, deploy the glass box.`}</P></Sec>

<div style={{marginTop:60,paddingTop:24,borderTop:`1px solid ${C.border}`}}><div style={{fontFamily:F.b,fontSize:12,color:C.light,lineHeight:1.8}}><strong>Sources:</strong> InterpretML GitHub (interpretml/interpret, 6.5k stars), interpret.ml docs. <strong>Academic:</strong> Hastie & Tibshirani 1986 (GAMs); Lou, Caruana, Gehrke KDD 2012 (Intelligible Models); Lou, Caruana, Gehrke, Hooker KDD 2013 (GA²M + FAST); Caruana, Lou, Gehrke, Koch, Sturm, Elhadad KDD 2015 (Healthcare); Nori, Jenkins, Koch, Caruana arXiv 1909.09223 2019 (InterpretML); Rudin, Nature MI 2019; Chang, Tan, Lengerich, Goldenberg, Caruana NeurIPS 2021 (GAM trustworthiness); CALMs arXiv 2602.16503 Feb 2026; Bordt et al. XAI4Sci AAAI-24 (TalkToEBM); arXiv 2507.03183 Jul 2025 (Transparent ML for meteorology). <strong>Regulatory:</strong> EU AI Act 2024, GDPR Art.22, ECOA.</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:12,marginTop:16}}><div style={{fontFamily:F.m,fontSize:11,color:C.light}}>InterpretML 0.6+ · MIT License · github.com/interpretml/interpret</div><div style={{fontFamily:F.m,fontSize:11,color:C.light}}>Length determined by information, not word count</div></div></div>
</div></div>);}
